spring:
  redis:
    #host: 192.168.83.129
    host: 192.168.101.7
    port: 6379
    #password: fastbee-smart
    database: 2
    # 连接超时时间
    timeout: 120s
    jedis:
      pool:
        # 最小空闲连接
        min-idle: 8
        # 最大空闲连接
        max-idle: 16
        # 最大连接数
        max-active: 32
        # 最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms